---
  - name: Realizando apt-get update
    apt:
     update_cache: yes
    become: yes 

  - name: Instalando a versão mais recente do Docker
    shell: curl -sS https://get.docker.com | sh
    become: yes

  - name: Reiniciando serviço do Docker
    systemd:
     state: restarted
     enabled: yes
     daemon_reload: yes
     name: docker
    become: yes 